services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: web_blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5431:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: